### ISSUE TITLE
Match molfeat styling to that of datamol 

### ISSUE THREAD

**Issue by cwognum** [datamol-io/molfeat#13]
![image](https://user-images.githubusercontent.com/28000055/227684314-091d942d-a997-4d4b-9e7f-722667c11dfb.png)

**TODO:**

- [x] Use a gradient in the header and footer. 
- [x] Update the logo to be thicker. 
- [x] Update primary and secondary colors
- [x] ~Add new diagram graphic too?~
- [x] Remove Valence from the footer
